import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(auth)/Navbar";
import Footer from "./(auth)/Footer";
import WrapperOfSessionProvider from "./_components/SessionProvider/WrapperOfSessionProvider";
import ToasterProvider from "./_components/toaster/Toaster";
import { getCartProducts, getWishlistProducts } from "./api/Services/Route.Services";
import CartContextProvider from "./_Context/CartContextProvider";
import WishlistContextProvider from "./_Context/WishlistContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const res = await getCartProducts()
  const response = await getWishlistProducts()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider res={res}>
          <WishlistContextProvider products={response}>
            <WrapperOfSessionProvider>
          <ToasterProvider />
          <Navbar />
          {children}
          <Footer />
        </WrapperOfSessionProvider>
          </WishlistContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
